dataset_name: NEU-DET

raw_dir: data/raw/NEU-DET
out_dir: data/processed

names:
  0: crazing
  1: inclusion
  2: patches
  3: pitted_surface
  4: rolled-in_scale
  5: scratches

split:
  train: 0.70
  val: 0.15
  test: 0.15
  seed: 1337
  stratify: true

overwrite: true
