name: yolov8n
model: yolov8n.pt
data: data/processed/data.yaml
seed: 1337

train:
  epochs: 100
  patience: 30
  imgsz: 640
  batch: 32
  workers: 8
  optimizer: auto
  lr0: 0.01
  lrf: 0.01
  cos_lr: true
  warmup_epochs: 3
  amp: true
  cache: disk
  deterministic: true
  val: true
  plots: true

  hsv_h: 0.0
  hsv_s: 0.0
  hsv_v: 0.3
  degrees: 10.0
  translate: 0.1
  scale: 0.5
  shear: 0.0
  perspective: 0.0
  flipud: 0.5
  fliplr: 0.5
  mosaic: 1.0
  close_mosaic: 10
  mixup: 0.0
  copy_paste: 0.0
